import Head from "next/head";
import React from "react";

import About from "../components/layout/About";
import Experience from "../components/layout/Experience";
import Header from "../components/layout/Header";
import Skills from "../components/layout/Skills";
import Profile from "../components/layout/Profile";

export default function Home() {
  return (
    <div className="bg-gray-800 h-screen text-white snap-y snap-mandatory overflow-scroll overflow-x-hidden z-0">
      <Head>
        <title>Adi Brisan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favi.ico" />
      </Head>
      {/* Header */}
      <Header />
      <section className="snap-center" id="profile">
        <Profile />
      </section>

      {/* About */}
      <section className="snap-center" id="about">
        <About />
      </section>

      {/* Experience */}
      <section className="snap-center" id="experience">
        <Experience />
      </section>

      {/* Skills */}
      <section className="snap-start" id="skills">
        <Skills />
      </section>

      {/* Projects */}

      {/* Contact Me */}
    </div>
  );
}
