import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Adi Brisan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favi.ico" />
      </Head>
      {/* Header */}

      {/* Profile */}

      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}
    </div>
  );
}
