import Head from "next/head";

import Header from "../components/layout/Header";
import Profile from "../components/layout/Profile";

export default function Home() {
  return (
    <div className="bg-gray-800 h-screen text-white snap-y snap-mandatory overflow-scroll overflow-x-hidden z-0">
      <Head>
        <title>Adi Brisan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favi.ico" />
      </Head>
      {/* Header */}
      <Header />
      <section className="snap-center" id="profile">
        <Profile />
      </section>

      {/* About */}

      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}
    </div>
  );
}
